CREATE TABLE IF NOT EXISTS `user`
(
    deviceId VARCHAR(255) PRIMARY KEY,
    xCoord DOUBLE NOT NULL DEFAULT 0,
    yCoord DOUBLE NOT NULL DEFAULT 0,
    lastLogin TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
